package me.xjcyan1de.cyanbot.world;

/**
 * Все типы в одном
 * @see com.github.steveice10.mc.protocol.data.game.entity.type.MobType
 * @see com.github.steveice10.mc.protocol.data.game.entity.type.object.ObjectType
 * @see com.github.steveice10.mc.protocol.packet.ingame.server.entity.spawn.ServerSpawnPlayerPacket
 */
public enum  EntityType {
    ELDER_GUARDIAN,
    WITHER_SKELETON,
    STRAY,
    HUSK,
    ZOMBIE_VILLAGER,
    SKELETON_HORSE,
    ZOMBIE_HORSE,
    ARMOR_STAND,
    DONKEY,
    MULE,
    EVOCATION_ILLAGER,
    VEX,
    VINDICATION_ILLAGER,
    ILLUSION_ILLAGER,
    CREEPER,
    SKELETON,
    SPIDER,
    GIANT_ZOMBIE,
    ZOMBIE,
    SLIME,
    GHAST,
    ZOMBIE_PIGMAN,
    ENDERMAN,
    CAVE_SPIDER,
    SILVERFISH,
    BLAZE,
    MAGMA_CUBE,
    ENDER_DRAGON,
    WITHER,
    BAT,
    WITCH,
    ENDERMITE,
    GUARDIAN,
    SHULKER,
    PIG,
    SHEEP,
    COW,
    CHICKEN,
    SQUID,
    WOLF,
    MOOSHROOM,
    SNOWMAN,
    OCELOT,
    IRON_GOLEM,
    HORSE,
    RABBIT,
    POLAR_BEAR,
    LLAMA,
    PARROT,
    VILLAGER,
    PLAYER, // игрока я сам вписал
    BOAT,
    ITEM,
    AREA_EFFECT_CLOUD,
    MINECART,
    PRIMED_TNT,
    ENDER_CRYSTAL,
    SNOWBALL,
    EGG,
    GHAST_FIREBALL,
    BLAZE_FIREBALL,
    ENDER_PEARL,
    WITHER_HEAD_PROJECTILE,
    SHULKER_BULLET,
    LLAMA_SPIT,
    FALLING_BLOCK,
    ITEM_FRAME,
    EYE_OF_ENDER,
    POTION,
    EXP_BOTTLE,
    FIREWORK_ROCKET,
    LEASH_KNOT,
    EVOCATION_FANGS,
    FISH_HOOK,
    SPECTRAL_ARROW,
    TIPPED_ARROW,
    DRAGON_FIREBALL
}
